<a href="https://colab.research.google.com/github/Zikirullo/ai-foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Pandas is Numpy library

# Pandasni pip yoki conda orqalik install qilishimiz mumkun
# Pandas can handle tabular data stored in spreadsheet or databases
# Use DataFrame build in method to turn it into table.

In [14]:
import pandas as pd
print(pd.__version__)

2.2.3

In [106]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferari", "Mers", "Kia"],
  'counts': [0, 7, 2, 10, 2, 6, 4]
}
df = pd.DataFrame(mydataset)
print(df)

     cars  counts
0     BMW       0
1   Volvo       7
2    Ford       2
3   Tesla      10
4  Ferari       2
5    Mers       6
6     Kia       4

In [23]:
# Head methodi defaul holda boshidan 5 malumotni korsatadi
# -1 hammasini faqat oxirgisini emas

df.head()

     cars  counts
0     BMW       3
1   Volvo       7
2    Ford       2
3   Tesla      10
4  Ferari       2

In [25]:
# tail default holda oxiridan 5 tani korsatidi

df.tail()

     cars  counts
2    Ford       2
3   Tesla      10
4  Ferari       2
5    Mers       6
6     Kia       4

In [27]:
# shape

df.shape

(7, 2)

In [29]:
# columns

df.columns

Index(['cars', 'counts'], dtype='object')

In [30]:
# dtypes

df.dtypes

cars      object
counts     int64
dtype: object

In [62]:
# describe() -> numerical columns only, statistical guidance

# std standard deviation -> raqamlar bir biridan qanchalik farq qiladi
# 25% -> raqamlarni 25% 2.5 dan kichik
# 50% -> raqamlarni 50% 4 dan kichik
# 75% -> raqamlarni 75% 6.5 dan kichik
# mex is max
# min is min

print(df)
print("-----------------")
df.describe()

     cars  counts
0     BMW       3
1   Volvo       7
2    Ford       2
3   Tesla      10
4  Ferari       2
5    Mers       6
6     Kia       4
-----------------

          counts
count   7.000000
mean    4.857143
std     2.968084
min     2.000000
25%     2.500000
50%     4.000000
75%     6.500000
max    10.000000

In [68]:
# iloc -> hohlagan malumotni select qilib olishimiz mumkun, ham row, ham column
# [1:4)

df.iloc[1:4]

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla      10

In [74]:
# loc -> tanlagan malumotimiz

df.loc[1, "cars"]
# df.loc[:, "counts"]

'Volvo'

In [91]:
df[df["cars"]  == "Tesla"]

# bu pandasda conditional selection, operation, filtering deyiladi

    cars  counts
3  Tesla      10

In [94]:
# mean()

df.mean(numeric_only=True)

counts    4.857143
dtype: float64

In [98]:
# sum()

df.sum( )

cars      BMWVolvoFordTeslaFerariMersKia
counts                                34
dtype: object

In [99]:
# min()

df.min()

cars      BMW
counts      2
dtype: object

In [101]:
# max()

df.max()

cars      Volvo
counts       10
dtype: object

In [102]:
# median()

df.median(numeric_only=True)

counts    4.0
dtype: float64

In [110]:
# count()

df.count()

cars      7
counts    7
dtype: int64

In [112]:
# std()

df.std(numeric_only=True)

counts    3.457222
dtype: float64

In [126]:
data_with_missings = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferari", None],
    "counts": [3, 7, None, 8, 9, None]
}
df_missing = pd.DataFrame(data_with_missings)
print(df_missing)

     cars  counts
0     BMW     3.0
1   Volvo     7.0
2    None     NaN
3   Tesla     8.0
4  Ferari     9.0
5    None     NaN

In [128]:
# isnull() + sum() = how many raws have null value

df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [131]:
# dropna() drops rows with no data

df_with_data = df_missing.dropna()

print(df_with_data)

     cars  counts
0     BMW     3.0
1   Volvo     7.0
3   Tesla     8.0
4  Ferari     9.0

In [133]:
df_missing.dropna(how="all")
df_missing.dropna(subset="counts")

     cars  counts
0     BMW     3.0
1   Volvo     7.0
3   Tesla     8.0
4  Ferari     9.0

In [139]:
# fillna() -> fills row with no data

df_missing.fillna(0)
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4   Ferari     9.0
5  unknown     0.0

In [161]:
# Real Dataset

df = pd.read_excel("test.xlsx")
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [158]:
df.to_excel("test.xlsx")

In [166]:
cars = pd.Series(["bmw", "tesla", "ferari"])
print(cars)

0       bmw
1     tesla
2    ferari
dtype: object